### ISSUE TITLE
Error when trying to make a new post

### ISSUE THREAD

**Issue by winterClover** [ebal/flatpress_tag_plugin#1]
The plugin works fine when I edit an existing post, but when I try to make a new post it throws a "fatal error"
![image](https://user-images.githubusercontent.com/66449394/129955369-8ac358c8-c904-4a8a-9230-b73c390cac20.png)

**Comment by ebal** [comment]
@winterClover there is too little info with your msg to go on.

I have tested tag_plugin 2.5.4-php7 with Ubuntu 20.04, php v7.4, apache v2.4.41 and FlatPress v1.2.1 and works perfectly fine.
