### ISSUE TITLE
Add the files for German language

### ISSUE THREAD

**Issue by Fraenkiman** [ebal/flatpress_tag_plugin#4]
Hello all,

in the course of the correction for Smarty 4 I recommend to add the files for German language.
I will gladly provide the appropriate files.

[lang.de-de.php.zip](https://github.com/ebal/flatpress_tag_plugin/files/9943830/lang.de-de.php.zip)

With best regards
Frank

**Comment by ebal** [comment]
added in 2.6.1 tag
